### ISSUE TITLE
stm32flash moved to SourceForge

### ISSUE THREAD

**Issue by opello** [ARMinARM/stm32flash#1]
Hi, I came across your repo while looking for stm32flash.  The [code.google.com project page](https://code.google.com/p/stm32flash/) now refers visitors to [a SourceForge project page](https://sourceforge.net/p/stm32flash/).

There is a [Git repo available on SourceForge](https://sourceforge.net/p/stm32flash/code/ci/master/tree/) that has a complete history if you would want to update yours.

**Comment by ARMinARM** [comment]
The build/install script in the arminarm repo now points to upstream stm32flash on sourceforge. Fixed and tested.

Thank you! :)

https://github.com/ARMinARM/arminarm/commit/d707d93eed7b0f92f07c7b6dde52cbd2f0ca0f31

@linmaogithub @mekatronik-achmadi @MinhTinkerer @nkaligin @RuanJG @yujiaao I leave this repo here as backup, but you might want to use upstream on sourceforge as well.
